# Generated by Django 2.2.4 on 2019-08-05 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drug',
            fields=[
                ('drug_id', models.AutoField(primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=250)),
                ('posology', models.CharField(max_length=250)),
                ('chemical_structure', models.TextField()),
                ('drug_bank_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='drug_state',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='pharmacogenes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gene_name', models.CharField(max_length=50)),
                ('protein', models.CharField(max_length=50)),
                ('function', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='study_type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='study',
            fields=[
                ('study_id', models.AutoField(primary_key=True, serialize=False)),
                ('study_title', models.CharField(max_length=250)),
                ('external_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agmp_app.study_type')),
            ],
        ),
        migrations.CreateModel(
            name='star_allele',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('star_annotation', models.CharField(max_length=50)),
                ('disease_phenotype', models.CharField(max_length=50)),
                ('chromosome', models.CharField(max_length=50)),
                ('disease_id', models.IntegerField()),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agmp_app.drug')),
                ('gene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agmp_app.pharmacogenes')),
                ('reference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agmp_app.study')),
            ],
        ),
        migrations.CreateModel(
            name='snp',
            fields=[
                ('snp_id', models.AutoField(primary_key=True, serialize=False)),
                ('rs_id', models.CharField(max_length=50)),
                ('allele', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agmp_app.drug')),
                ('gene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agmp_app.pharmacogenes')),
                ('reference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agmp_app.study')),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agmp_app.drug_state'),
        ),
    ]
