# Generated by Django 2.2.2 on 2019-08-06 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0005_auto_20190805_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snp',
            name='drug_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agmp_app.drug'),
        ),
        migrations.AlterField(
            model_name='snp',
            name='gene_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='agmp_app.pharmacogenes'),
        ),
        migrations.AlterField(
            model_name='snp',
            name='reference_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='agmp_app.study'),
        ),
    ]
